// Thin fetch wrapper shared by every page. Normalises every response into an envelope so
// widgets can render loading / empty / error / "not available yet" states consistently
// (phase6-workspace-ui: "no mocked data in the shipped build").
//
// Endpoints that exist in web/src/api/schemas.js (generated by `make gen-schemas` from the
// live OpenAPI doc) are validated at runtime with their zod schema. Endpoints from the P6 UI
// spec that the backend has not implemented yet come back as FastAPI's default
// `{"detail":"Not Found"}` 404 — we surface that as `kind: "not_implemented"` rather than as
// a generic error, so the UI can say so honestly instead of guessing.

// `VITE_API_BASE` unset (local default build, no .env file) -> the local FastAPI dev server.
// `VITE_API_BASE=""` set explicitly (cloud build, web/.env.cloud) -> same-origin relative paths
// (the Lambda serves the API and the built React app from the same origin). A plain `||` here
// would treat "" as falsy and wrongly fall back to localhost in the cloud build.
const RAW_API_BASE = import.meta.env.VITE_API_BASE;
export const API_BASE = RAW_API_BASE === undefined ? "http://localhost:8000" : RAW_API_BASE;

export const READ_ONLY = import.meta.env.VITE_READ_ONLY === "true";

/** @typedef {{ok: true, data: any, validated: boolean, issues?: any[]}} ApiOk */
/** @typedef {{ok: false, kind: "not_implemented"|"not_found"|"network"|"error"|"invalid", message: string, status?: number}} ApiErr */

/**
 * @param {string} path
 * @param {{schema?: import("zod").ZodTypeAny, params?: Record<string, any>, signal?: AbortSignal, method?: string, body?: any}} [opts]
 * @returns {Promise<ApiOk|ApiErr>}
 */
export async function apiFetch(path, opts = {}) {
  const { schema, params, signal, method = "GET", body } = opts;
  let url = `${API_BASE}${path}`;
  if (params && Object.keys(params).length) {
    const usp = new URLSearchParams();
    for (const [k, v] of Object.entries(params)) {
      if (v === undefined || v === null || v === "") continue;
      usp.set(k, String(v));
    }
    const qs = usp.toString();
    if (qs) url += (url.includes("?") ? "&" : "?") + qs;
  }

  let res;
  // GETs are retried briefly on 429/503: the cloud demo's Lambda has a small concurrency limit,
  // so a page's first burst of parallel requests can be throttled for a moment.
  for (let attempt = 0; ; attempt++) {
    try {
      res = await fetch(url, {
        method,
        signal,
        headers: body ? { "Content-Type": "application/json" } : undefined,
        body: body ? JSON.stringify(body) : undefined,
      });
    } catch (e) {
      if (e?.name === "AbortError") throw e;
      return { ok: false, kind: "network", message: `Cannot reach the server. Please check that the backend is running and try again.` };
    }
    if (method !== "GET" || (res.status !== 429 && res.status !== 503) || attempt >= 2) break;
    await new Promise((r) => setTimeout(r, 400 * (attempt + 1) + Math.random() * 300));
  }

  let json = null;
  const text = await res.text();
  if (text) {
    try {
      json = JSON.parse(text);
    } catch {
      json = null;
    }
  }

  if (!res.ok) {
    if (res.status === 404 && (!json || json.detail === "Not Found")) {
      return { ok: false, kind: "not_implemented", message: `${path} is not implemented on the API yet.`, status: 404 };
    }
    const message = json?.detail ? (typeof json.detail === "string" ? json.detail : JSON.stringify(json.detail)) : res.statusText;
    return { ok: false, kind: "not_found", message: message || `Request failed (${res.status})`, status: res.status };
  }

  if (schema) {
    const parsed = schema.safeParse(json);
    if (!parsed.success) {
      console.warn(`Response for ${path} did not match its generated schema`, parsed.error.issues);
      return { ok: true, data: json, validated: false, issues: parsed.error.issues };
    }
    return { ok: true, data: parsed.data, validated: true };
  }
  return { ok: true, data: json, validated: false };
}

export function apiGet(path, params, schema, signal) {
  return apiFetch(path, { params, schema, signal });
}

export function apiPost(path, body, schema, signal) {
  return apiFetch(path, { method: "POST", body, schema, signal });
}

/** Binary/image asset URL (webp page render, satellite chip, PDF export...). */
export function assetUrl(path) {
  return `${API_BASE}${path}`;
}
