// AUTO-GENERATED by `make gen-schemas` (scripts/gen_schemas.py) from the FastAPI OpenAPI document.
// Do not edit by hand — regenerate after any app/api schema change (D-011).
import { z } from "zod";

export const AttachmentSchema = z.lazy(() => (z.object({
  "id": z.string(),
  "kind": z.enum(["pdf", "image", "geojson", "csv", "text"]).nullable(),
  "name": z.string().optional(),
  "path": z.string().nullable(),
  "media_type": z.string().nullable(),
  "size_bytes": z.number().int().nullable(),
})));
export const Body_ingest_document_ingest_documents_postSchema = z.lazy(() => (z.object({
  "file": z.string(),
  "village": z.string().nullable(),
  "doc_type": z.string().nullable(),
})));
export const ChartSpecSchema = z.lazy(() => (z.object({
  "id": z.string(),
  "title": z.string(),
  "type": z.enum(["bar", "stacked_bar", "line", "pie"]),
  "x": z.string(),
  "y": z.array(z.string()),
  "data": z.array(z.record(z.any())),
  "claim_ids": z.array(z.string()).optional(),
})));
export const CheckResultSchema = z.lazy(() => (z.object({
  "name": z.string(),
  "passed": z.boolean(),
  "detail": z.string().optional(),
})));
export const ClarifyRequestSchema = z.lazy(() => (z.object({
  "answer": z.string(),
})));
export const ClassifierSummaryResponseSchema = z.lazy(() => (z.object({
  "metrics": z.array(z.record(z.any())),
  "live_distribution": z.array(z.record(z.any())),
  "folder_vs_classified_mismatch": z.number().int(),
  "source": z.string().optional(),
})));
export const ColumnSchema = z.lazy(() => (z.object({
  "key": z.string(),
  "label": z.string(),
  "type": z.enum(["string", "number", "date", "bool"]).optional(),
})));
export const DecisionSchema = z.lazy(() => (z.object({
  "id": z.string(),
  "date": z.string().nullable(),
  "decision": z.string(),
  "by": z.string().nullable(),
  "context": z.string().nullable(),
})));
export const DecisionsResponseSchema = z.lazy(() => (z.object({
  "items": z.array(DecisionSchema),
  "source": z.string().optional(),
})));
export const DidRowSchema = z.lazy(() => (z.object({
  "event": z.string(),
  "metric": z.string(),
  "season_scope": z.string(),
  "event_date": z.string().nullable(),
  "n_pre": z.number().int().nullable(),
  "n_post": z.number().int().nullable(),
  "pre_diff": z.number().nullable(),
  "post_diff": z.number().nullable(),
  "did": z.number().nullable(),
  "ci_lo": z.number().nullable(),
  "ci_hi": z.number().nullable(),
  "farmland_like_p": z.number().nullable(),
})));
export const DocumentListResponseSchema = z.lazy(() => (z.object({
  "items": z.array(DocumentSummarySchema),
  "total": z.number().int(),
  "limit": z.number().int(),
  "offset": z.number().int(),
})));
export const DocumentSummarySchema = z.lazy(() => (z.object({
  "id": z.number().int(),
  "sha256": z.string(),
  "path": z.string(),
  "classified_type": z.string().nullable(),
  "scheme_relevance": z.string().nullable(),
  "village": z.string().nullable(),
  "unit_no": z.string().nullable(),
  "block_no": z.string().nullable(),
  "doc_no": z.string().nullable(),
  "doc_date": z.string().nullable(),
  "pages": z.number().int(),
  "status": z.string(),
  "stage": z.string().nullable(),
  "folder_label": z.string().nullable(),
  "folder_type_mismatch": z.boolean().optional(),
})));
export const EvalSummaryResponseSchema = z.lazy(() => (z.object({
  "rows": z.array(z.record(z.any())),
  "files": z.record(z.any()),
  "source": z.string().optional(),
})));
export const EvidenceSchema = z.lazy(() => (z.object({
  "kind": z.enum(["page_bbox", "sql", "layer_feature", "raster", "satellite_chip", "timeseries", "document"]),
  "ref": z.string(),
  "excerpt": z.string().nullable(),
  "bbox": z.array(z.number()).nullable(),
  "page": z.number().int().nullable(),
  "document_id": z.number().int().nullable(),
})));
export const EvidenceGroupSchema = z.lazy(() => (z.object({
  "claim_id": z.string(),
  "items": z.array(EvidenceSchema),
})));
export const EvidencePackResponseSchema = z.lazy(() => (z.object({
  "finding_id": z.number().int(),
  "pack": z.record(z.any()),
  "source": z.string().optional(),
})));
export const EvidenceResponseSchema = z.lazy(() => (z.object({
  "extraction_id": z.number().int(),
  "document_id": z.number().int().nullable(),
  "page_id": z.number().int().nullable(),
  "page_no": z.number().int().nullable(),
  "page_ref": z.string().nullable(),
  "schema_name": z.string(),
  "doc_type": z.string().nullable(),
  "bbox": z.array(z.number()).nullable(),
  "bbox_method": z.string().nullable(),
  "extractor": z.string().nullable(),
  "privacy_tier": z.string(),
  "confidence": z.number().nullable(),
  "review_status": z.string(),
  "row": z.record(z.any()),
  "owners": z.array(OwnerRefSchema).optional(),
  "masked": z.boolean().optional(),
})));
export const ExampleQuerySchema = z.lazy(() => (z.object({
  "id": z.string(),
  "text": z.string(),
  "category": z.string().nullable(),
})));
export const ExamplesResponseSchema = z.lazy(() => (z.object({
  "items": z.array(ExampleQuerySchema),
})));
export const FindingItemSchema = z.lazy(() => (z.object({
  "id": z.number().int(),
  "finding_key": z.string(),
  "category": z.string(),
  "severity": z.string(),
  "confidence": z.number(),
  "parcel_uid": z.string().nullable(),
  "village": z.string().nullable(),
  "unit_id": z.number().int().nullable(),
  "block_id": z.number().int().nullable(),
  "title": z.string(),
  "evidence_level": z.string(),
  "verdict": z.string().nullable(),
  "status": z.string(),
  "caveats": z.array(z.string()).optional(),
  "created_at": z.string(),
})));
export const FindingListResponseSchema = z.lazy(() => (z.object({
  "items": z.array(FindingItemSchema),
  "total": z.number().int(),
  "limit": z.number().int(),
  "offset": z.number().int(),
  "source": z.string().optional(),
})));
export const FindingSummaryResponseSchema = z.lazy(() => (z.object({
  "items": z.array(FindingSummaryRowSchema),
  "source": z.string().optional(),
})));
export const FindingSummaryRowSchema = z.lazy(() => (z.object({
  "category": z.string(),
  "severity": z.string(),
  "evidence_level": z.string(),
  "n": z.number().int(),
  "avg_conf": z.number(),
})));
export const HTTPValidationErrorSchema = z.lazy(() => (z.object({
  "detail": z.array(ValidationErrorSchema).optional(),
})));
export const IdleLandResponseSchema = z.lazy(() => (z.object({
  "items": z.array(IdleLandRowSchema),
  "source": z.string().optional(),
})));
export const IdleLandRowSchema = z.lazy(() => (z.object({
  "finding_id": z.number().int(),
  "village": z.string().nullable(),
  "unit_id": z.number().int().nullable(),
  "block_id": z.number().int().nullable(),
  "idle_ha": z.number().nullable(),
  "n_parcels": z.number().int().nullable(),
  "oldest_possession": z.string().nullable(),
  "min_major_road_km": z.number().nullable(),
  "min_substation_km": z.number().nullable(),
  "evidence_level": z.string(),
  "confidence": z.number(),
})));
export const IngestDocumentAcceptedSchema = z.lazy(() => (z.object({
  "job_id": z.number().int(),
  "status": z.enum(["queued", "duplicate"]),
  "duplicate_of": z.number().int().nullable(),
})));
export const IngestJobSchema = z.lazy(() => (z.object({
  "id": z.number().int(),
  "kind": z.enum(["document", "satellite"]),
  "status": z.enum(["queued", "running", "done", "failed", "duplicate"]),
  "filename": z.string().nullable(),
  "created_at": z.string(),
  "started_at": z.string().nullable(),
  "finished_at": z.string().nullable(),
  "document_id": z.number().int().nullable(),
  "stages": z.array(IngestStageSchema),
  "result": z.record(z.any()).nullable(),
  "error": z.string().nullable(),
})));
export const IngestJobListResponseSchema = z.lazy(() => (z.object({
  "jobs": z.array(IngestJobSchema),
})));
export const IngestStageSchema = z.lazy(() => (z.object({
  "name": z.string(),
  "status": z.enum(["pending", "running", "done", "skipped", "failed"]),
  "started_at": z.string().nullable(),
  "finished_at": z.string().nullable(),
  "detail": z.string().nullable(),
})));
export const KpiSchema = z.lazy(() => (z.object({
  "id": z.string(),
  "label": z.string(),
  "value": z.any(),
  "unit": z.string().nullable(),
  "claim_id": z.string(),
  "status": z.enum(["verified", "downgraded", "review"]),
  "confidence": z.number(),
})));
export const KpiValueSchema = z.lazy(() => (z.object({
  "id": z.string(),
  "label": z.string(),
  "value": z.any(),
  "unit": z.string().nullable(),
  "source": z.string(),
  "breakdown": z.record(z.any()).nullable(),
})));
export const LedgerVerifyResponseSchema = z.lazy(() => (z.object({
  "run_id": z.string(),
  "ok": z.boolean(),
  "first_bad_seq": z.number().int().nullable(),
  "n_entries": z.number().int(),
  "head_hash": z.string().nullable(),
})));
export const LegendItemSchema = z.lazy(() => (z.object({
  "value": z.any(),
  "label": z.string(),
  "color": z.string(),
})));
export const MapLayerSchema = z.lazy(() => (z.object({
  "id": z.string(),
  "title": z.string(),
  "kind": z.enum(["parcels", "polygons", "points", "reference"]),
  "geojson": z.record(z.any()).nullable(),
  "ref_layer": z.string().nullable(),
  "color_by": z.string().nullable(),
  "legend": z.array(LegendItemSchema).optional(),
})));
export const MapSpecSchema = z.lazy(() => (z.object({
  "bbox": z.array(z.number()).nullable(),
  "layers": z.array(MapLayerSchema).optional(),
  "time_slider": TimeSliderSchema.nullable(),
})));
export const NarrativeSchema = z.lazy(() => (z.object({
  "en": z.string().optional(),
  "ta": z.string().nullable(),
  "claim_refs": z.array(z.string()).optional(),
})));
export const OwnerRefSchema = z.lazy(() => (z.object({
  "position": z.number().int(),
  "token": z.string(),
  "relation": z.string().nullable(),
  "legal_heirs": z.boolean().optional(),
  "name": z.string().nullable(),
})));
export const ParcelDetailSchema = z.lazy(() => (z.object({
  "parcel_uid": z.string(),
  "village": z.string().nullable(),
  "kide": z.string().nullable(),
  "survey_no": z.string().nullable(),
  "sub_div": z.string().nullable(),
  "unit_id": z.number().int().nullable(),
  "block_id": z.number().int().nullable(),
  "area_ha_gis": z.number().nullable(),
  "area_ha_utm": z.number().nullable(),
  "inside_park_boundary": z.boolean().nullable(),
  "current_stage": z.string().nullable(),
  "stage_entered": z.string().nullable(),
  "days_in_stage": z.number().int().nullable(),
  "evidence_level": z.string().nullable(),
  "stalled_flag": z.string().nullable(),
  "n_findings": z.number().int().optional(),
  "source": z.string().optional(),
})));
export const ParcelExtractionRowSchema = z.lazy(() => (z.object({
  "extraction_id": z.number().int(),
  "fact_type": z.string().nullable(),
  "document_id": z.number().int().nullable(),
  "page_no": z.number().int().nullable(),
  "bbox": z.array(z.number()).nullable(),
  "bbox_method": z.string().nullable(),
  "confidence": z.number().nullable(),
  "self_consistency": z.string().nullable(),
  "owner_read_status": z.string().nullable(),
  "review_status": z.string().nullable(),
  "row": z.record(z.any()),
})));
export const ParcelExtractionsResponseSchema = z.lazy(() => (z.object({
  "parcel_uid": z.string(),
  "items": z.array(ParcelExtractionRowSchema),
  "total": z.number().int(),
  "source": z.string().optional(),
})));
export const ParcelSatelliteResponseSchema = z.lazy(() => (z.object({
  "parcel_uid": z.string(),
  "did": z.array(DidRowSchema),
  "season_states": z.array(SeasonStateSchema),
  "chips": z.array(z.string()),
  "source": z.string().optional(),
})));
export const ParcelTimelineResponseSchema = z.lazy(() => (z.object({
  "parcel_uid": z.string(),
  "events": z.array(app__api__schemas__TimelineEventSchema),
  "series": z.array(SeriesPointSchema),
  "season_states": z.array(SeasonStateSchema),
  "source": z.string().optional(),
})));
export const ProgressResponseSchema = z.lazy(() => (z.object({
  "overall_pct": z.string().nullable(),
  "phases": z.array(z.record(z.any())),
  "raw_markdown": z.string(),
  "source": z.string().optional(),
})));
export const ReviewDecisionRequestSchema = z.lazy(() => (z.object({
  "decision": z.enum(["approved", "corrected", "rejected"]),
  "corrected_value": z.record(z.any()).nullable(),
  "decided_by": z.string().nullable(),
})));
export const ReviewDecisionResponseSchema = z.lazy(() => (z.object({
  "id": z.number().int(),
  "status": z.string(),
  "extraction_id": z.number().int().nullable(),
  "review_status": z.string().nullable(),
})));
export const ReviewItemSchema = z.lazy(() => (z.object({
  "id": z.number().int(),
  "content_hash": z.string(),
  "document_id": z.number().int().nullable(),
  "page_id": z.number().int().nullable(),
  "page_ref": z.string().nullable(),
  "extraction_id": z.number().int().nullable(),
  "reason": z.string(),
  "detail": z.record(z.any()).optional(),
  "status": z.enum(["open", "decided", "dismissed"]),
  "decided_value": z.record(z.any()).nullable(),
  "decided_by": z.string().nullable(),
  "decided_at": z.string().nullable(),
  "created_at": z.string(),
})));
export const ReviewListResponseSchema = z.lazy(() => (z.object({
  "items": z.array(ReviewItemSchema),
  "total": z.number().int(),
})));
export const RouteTraceEntrySchema = z.lazy(() => (z.object({
  "step_id": z.string(),
  "task": z.string(),
  "choice": z.string().nullable(),
  "reason": z.string().optional(),
  "candidates": z.array(z.string()).optional(),
  "filtered": z.array(z.record(z.any())).optional(),
  "attempts": z.array(z.record(z.any())).optional(),
  "latency_ms": z.number().int().optional(),
  "shadow_cost_usd": z.number().optional(),
  "scores": z.record(z.any()).optional(),
  "privacy_tier": z.string().nullable(),
  "effective_tier": z.string().nullable(),
  "tokens_in": z.number().int().optional(),
  "tokens_out": z.number().int().optional(),
  "actual_cost_usd": z.number().optional(),
})));
export const RouterChainsResponseSchema = z.lazy(() => (z.object({
  "tasks": z.array(z.record(z.any())),
  "source": z.string().optional(),
})));
export const RouterModelsResponseSchema = z.lazy(() => (z.object({
  "models": z.array(z.record(z.any())),
  "doctor": z.record(z.any()).nullable(),
  "source": z.string().optional(),
})));
export const RouterUsageResponseSchema = z.lazy(() => (z.object({
  "by_model_task": z.array(z.record(z.any())),
  "latency": z.array(z.record(z.any())),
  "pii_audit": z.record(z.any()),
  "source": z.string().optional(),
})));
export const RunCreateRequestSchema = z.lazy(() => (z.object({
  "request": z.string(),
  "attachments": z.array(AttachmentSchema).optional(),
  "workspace_id": z.string().nullable(),
  "domain": z.enum(["land_acquisition", "agri_claims"]).nullable(),
  "lang": z.enum(["en", "ta"]).nullable(),
  "chaos": z.string().nullable(),
})));
export const RunCreateResponseSchema = z.lazy(() => (z.object({
  "run_id": z.string(),
})));
export const RunListResponseSchema = z.lazy(() => (z.object({
  "items": z.array(RunSummarySchema),
  "total": z.number().int(),
  "limit": z.number().int(),
  "offset": z.number().int(),
})));
export const RunPublicStateSchema = z.lazy(() => (z.object({
  "run_id": z.string(),
  "workspace_id": z.string().nullable(),
  "contract_version": z.string().optional(),
  "request": z.string(),
  "lang": z.enum(["en", "ta"]).optional(),
  "domain": z.string().optional(),
  "attachments": z.array(AttachmentSchema).optional(),
  "status": z.enum(["queued", "running", "clarify", "done", "failed"]),
  "created_at": z.string(),
  "updated_at": z.string(),
  "slots": z.record(z.any()).optional(),
  "missing_info": z.array(z.record(z.any())).optional(),
  "assumptions": z.array(z.string()).optional(),
  "plan": z.record(z.any()).nullable(),
  "steps": z.record(z.any()).optional(),
  "claims": z.array(z.record(z.any())).optional(),
  "critic": z.array(z.record(z.any())).optional(),
  "verdicts": z.record(z.any()).optional(),
  "reroutes": z.number().int().optional(),
  "workspace": z.record(z.any()).nullable(),
  "narrative": z.record(z.any()).optional(),
  "route_trace": z.array(z.record(z.any())).optional(),
  "telemetry": z.record(z.any()).optional(),
  "ledger_head": z.string().nullable(),
  "errors": z.array(z.record(z.any())).optional(),
  "degraded": z.boolean().optional(),
})));
export const RunSummarySchema = z.lazy(() => (z.object({
  "id": z.string(),
  "workspace_id": z.string().nullable(),
  "status": z.string(),
  "request": z.string().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
})));
export const RunTraceResponseSchema = z.lazy(() => (z.object({
  "run_id": z.string(),
  "route_trace": z.array(z.record(z.any())),
  "critic": z.array(z.record(z.any())),
  "judge": z.array(z.record(z.any())),
  "fallbacks": z.array(z.record(z.any())),
  "ledger_head": z.string().nullable(),
  "router_log": z.array(z.record(z.any())).optional(),
  "source": z.string().optional(),
})));
export const SatelliteRefreshAcceptedSchema = z.lazy(() => (z.object({
  "job_id": z.number().int(),
})));
export const SatelliteRefreshRequestSchema = z.lazy(() => (z.object({
  "max_scenes": z.number().int().nullable(),
})));
export const SatelliteStatusResponseSchema = z.lazy(() => (z.object({
  "latest_scene_date": z.string().nullable(),
  "scene_count": z.number().int(),
  "last_refresh_at": z.string().nullable(),
  "running_job_id": z.number().int().nullable(),
})));
export const SeasonStateSchema = z.lazy(() => (z.object({
  "ag_year": z.number().int(),
  "season": z.string(),
  "state": z.string().nullable(),
  "p_state": z.number().nullable(),
  "route": z.string().nullable(),
  "needs_field": z.boolean().optional(),
})));
export const SeriesPointSchema = z.lazy(() => (z.object({
  "date": z.string(),
  "ndvi": z.number().nullable(),
  "bsi": z.number().nullable(),
  "ndwi": z.number().nullable(),
  "supported": z.boolean().nullable(),
})));
export const SqlEntrySchema = z.lazy(() => (z.object({
  "step_id": z.string(),
  "sql": z.string(),
})));
export const StatsOverviewResponseSchema = z.lazy(() => (z.object({
  "kpis": z.array(KpiValueSchema),
  "phase_status": z.record(z.any()).nullable(),
  "generated_at": z.string(),
})));
export const TableSpecSchema = z.lazy(() => (z.object({
  "id": z.string(),
  "title": z.string(),
  "columns": z.array(ColumnSchema),
  "rows": z.array(z.record(z.any())),
  "claim_ids": z.array(z.string()).optional(),
  "sql": z.string().nullable(),
})));
export const TimeSliderSchema = z.lazy(() => (z.object({
  "field": z.string().optional(),
  "values": z.array(z.string()).optional(),
})));
export const TimelineEvent_InputSchema = z.lazy(() => (z.object({
  "date": z.string(),
  "stage": z.string(),
  "label": z.string().optional(),
  "evidence_ref": z.string().nullable(),
})));
export const TimelineSpec_InputSchema = z.lazy(() => (z.object({
  "subject": z.string(),
  "events": z.array(TimelineEvent_InputSchema).optional(),
  "series": z.array(z.record(z.any())).optional(),
})));
export const TimelineSpec_OutputSchema = z.lazy(() => (z.object({
  "subject": z.string(),
  "events": z.array(app__agent__state__TimelineEventSchema).optional(),
  "series": z.array(z.record(z.any())).optional(),
})));
export const ValidationErrorSchema = z.lazy(() => (z.object({
  "loc": z.array(z.union([z.string(), z.number().int()])),
  "msg": z.string(),
  "type": z.string(),
  "input": z.any().optional(),
  "ctx": z.record(z.any()).optional(),
})));
export const VerificationClaimSchema = z.lazy(() => (z.object({
  "claim_id": z.string(),
  "verdict": z.enum(["ACCEPT", "DOWNGRADE", "REROUTE", "REVIEW"]).nullable(),
  "confidence": z.number(),
  "checks": z.array(CheckResultSchema).optional(),
  "critic": z.record(z.any()).nullable(),
})));
export const VerificationSpecSchema = z.lazy(() => (z.object({
  "summary": VerificationSummarySchema.optional(),
  "claims": z.array(VerificationClaimSchema).optional(),
})));
export const VerificationSummarySchema = z.lazy(() => (z.object({
  "accepted": z.number().int().optional(),
  "downgraded": z.number().int().optional(),
  "review": z.number().int().optional(),
  "rerouted": z.number().int().optional(),
})));
export const WorkspaceCreateSchema = z.lazy(() => (z.object({
  "name": z.string().optional(),
  "spec": WorkspaceSpec_InputSchema,
  "created_by": z.string().nullable(),
})));
export const WorkspaceRecordSchema = z.lazy(() => (z.object({
  "id": z.string(),
  "name": z.string(),
  "version": z.number().int(),
  "spec": WorkspaceSpec_OutputSchema,
  "ledger_head": z.string().nullable(),
  "created_by": z.string().nullable(),
  "created_at": z.string(),
  "updated_at": z.string(),
})));
export const WorkspaceSpec_InputSchema = z.lazy(() => (z.object({
  "spec_version": z.string().optional(),
  "workspace_id": z.string().nullable(),
  "version": z.number().int().nullable(),
  "title": z.string(),
  "domain": z.string(),
  "run_id": z.string(),
  "created_at": z.string(),
  "ledger_head": z.string().nullable(),
  "lang": z.enum(["en", "ta"]).optional(),
  "kpis": z.array(KpiSchema).optional(),
  "map": MapSpecSchema.optional(),
  "tables": z.array(TableSpecSchema).optional(),
  "charts": z.array(ChartSpecSchema).optional(),
  "timeline": TimelineSpec_InputSchema.nullable(),
  "narrative": NarrativeSchema.optional(),
  "evidence": z.array(EvidenceGroupSchema).optional(),
  "verification": VerificationSpecSchema.optional(),
  "sql": z.array(SqlEntrySchema).optional(),
  "route_trace": z.array(RouteTraceEntrySchema).optional(),
  "caveats": z.array(z.string()).optional(),
})));
export const WorkspaceSpec_OutputSchema = z.lazy(() => (z.object({
  "spec_version": z.string().optional(),
  "workspace_id": z.string().nullable(),
  "version": z.number().int().nullable(),
  "title": z.string(),
  "domain": z.string(),
  "run_id": z.string(),
  "created_at": z.string(),
  "ledger_head": z.string().nullable(),
  "lang": z.enum(["en", "ta"]).optional(),
  "kpis": z.array(KpiSchema).optional(),
  "map": MapSpecSchema.optional(),
  "tables": z.array(TableSpecSchema).optional(),
  "charts": z.array(ChartSpecSchema).optional(),
  "timeline": TimelineSpec_OutputSchema.nullable(),
  "narrative": NarrativeSchema.optional(),
  "evidence": z.array(EvidenceGroupSchema).optional(),
  "verification": VerificationSpecSchema.optional(),
  "sql": z.array(SqlEntrySchema).optional(),
  "route_trace": z.array(RouteTraceEntrySchema).optional(),
  "caveats": z.array(z.string()).optional(),
})));
export const WorkspaceUpdateSchema = z.lazy(() => (z.object({
  "spec": WorkspaceSpec_InputSchema,
  "name": z.string().nullable(),
})));
export const app__agent__state__TimelineEventSchema = z.lazy(() => (z.object({
  "date": z.string(),
  "stage": z.string(),
  "label": z.string().optional(),
  "evidence_ref": z.string().nullable(),
})));
export const app__api__schemas__TimelineEventSchema = z.lazy(() => (z.object({
  "event_id": z.number().int().nullable(),
  "stage": z.string(),
  "event_date": z.string().nullable(),
  "date_precision": z.string().nullable(),
  "document_id": z.number().int().nullable(),
  "extraction_id": z.number().int().nullable(),
  "link_kind": z.string().nullable(),
})));
export const endpoints = [
  { method: "POST", path: "/runs", operationId: "create_run_runs_post", requestSchema: RunCreateRequestSchema, responseSchema: RunCreateResponseSchema },
  { method: "GET", path: "/runs", operationId: "list_runs_runs_get", requestSchema: null, responseSchema: RunListResponseSchema },
  { method: "GET", path: "/runs/{run_id}/events", operationId: "run_events_runs__run_id__events_get", requestSchema: null, responseSchema: null },
  { method: "GET", path: "/runs/{run_id}", operationId: "get_run_runs__run_id__get", requestSchema: null, responseSchema: RunPublicStateSchema },
  { method: "POST", path: "/runs/{run_id}/clarify", operationId: "clarify_run_runs__run_id__clarify_post", requestSchema: ClarifyRequestSchema, responseSchema: RunCreateResponseSchema },
  { method: "GET", path: "/runs/{run_id}/trace", operationId: "get_run_trace_runs__run_id__trace_get", requestSchema: null, responseSchema: RunTraceResponseSchema },
  { method: "POST", path: "/ledger/verify", operationId: "verify_ledger_ledger_verify_post", requestSchema: null, responseSchema: LedgerVerifyResponseSchema },
  { method: "GET", path: "/workspaces", operationId: "list_workspaces_workspaces_get", requestSchema: null, responseSchema: null },
  { method: "POST", path: "/workspaces", operationId: "create_workspace_workspaces_post", requestSchema: WorkspaceCreateSchema, responseSchema: WorkspaceRecordSchema },
  { method: "GET", path: "/workspaces/{workspace_id}", operationId: "get_workspace_workspaces__workspace_id__get", requestSchema: null, responseSchema: WorkspaceRecordSchema },
  { method: "PUT", path: "/workspaces/{workspace_id}", operationId: "update_workspace_workspaces__workspace_id__put", requestSchema: WorkspaceUpdateSchema, responseSchema: WorkspaceRecordSchema },
  { method: "GET", path: "/workspaces/{workspace_id}/versions/{version}", operationId: "get_workspace_version_workspaces__workspace_id__versions__version__get", requestSchema: null, responseSchema: WorkspaceRecordSchema },
  { method: "POST", path: "/workspaces/{workspace_id}/export", operationId: "export_workspace_route_workspaces__workspace_id__export_post", requestSchema: null, responseSchema: null },
  { method: "GET", path: "/documents", operationId: "list_documents_documents_get", requestSchema: null, responseSchema: DocumentListResponseSchema },
  { method: "GET", path: "/classifier/summary", operationId: "classifier_summary_classifier_summary_get", requestSchema: null, responseSchema: ClassifierSummaryResponseSchema },
  { method: "GET", path: "/documents/{document_id}/pages/{page_no}.webp", operationId: "get_page_preview_documents__document_id__pages__page_no__webp_get", requestSchema: null, responseSchema: null },
  { method: "GET", path: "/evidence/{extraction_id}", operationId: "get_evidence_evidence__extraction_id__get", requestSchema: null, responseSchema: EvidenceResponseSchema },
  { method: "GET", path: "/layers/{name}.geojson", operationId: "get_layer_layers__name__geojson_get", requestSchema: null, responseSchema: null },
  { method: "GET", path: "/chips/{parcel_uid}/{date}.png", operationId: "get_chip_chips__parcel_uid___date__png_get", requestSchema: null, responseSchema: null },
  { method: "GET", path: "/review-queue", operationId: "review_queue_review_queue_get", requestSchema: null, responseSchema: ReviewListResponseSchema },
  { method: "POST", path: "/review/{review_id}", operationId: "decide_review_review__review_id__post", requestSchema: ReviewDecisionRequestSchema, responseSchema: ReviewDecisionResponseSchema },
  { method: "GET", path: "/examples", operationId: "list_examples_examples_get", requestSchema: null, responseSchema: ExamplesResponseSchema },
  { method: "GET", path: "/parcels/{parcel_uid}/timeline", operationId: "get_parcel_timeline_parcels__parcel_uid__timeline_get", requestSchema: null, responseSchema: ParcelTimelineResponseSchema },
  { method: "GET", path: "/parcels/{parcel_uid}/extractions", operationId: "get_parcel_extractions_parcels__parcel_uid__extractions_get", requestSchema: null, responseSchema: ParcelExtractionsResponseSchema },
  { method: "GET", path: "/parcels/{parcel_uid}/satellite", operationId: "get_parcel_satellite_parcels__parcel_uid__satellite_get", requestSchema: null, responseSchema: ParcelSatelliteResponseSchema },
  { method: "GET", path: "/parcels/{parcel_uid}/findings", operationId: "get_parcel_findings_parcels__parcel_uid__findings_get", requestSchema: null, responseSchema: null },
  { method: "GET", path: "/parcels/{parcel_uid}", operationId: "get_parcel_parcels__parcel_uid__get", requestSchema: null, responseSchema: ParcelDetailSchema },
  { method: "GET", path: "/findings", operationId: "list_findings_findings_get", requestSchema: null, responseSchema: FindingListResponseSchema },
  { method: "GET", path: "/findings/summary", operationId: "findings_summary_findings_summary_get", requestSchema: null, responseSchema: FindingSummaryResponseSchema },
  { method: "GET", path: "/idle-land", operationId: "idle_land_idle_land_get", requestSchema: null, responseSchema: IdleLandResponseSchema },
  { method: "GET", path: "/findings/{finding_id}/evidence-pack", operationId: "get_evidence_pack_findings__finding_id__evidence_pack_get", requestSchema: null, responseSchema: EvidencePackResponseSchema },
  { method: "GET", path: "/stats/overview", operationId: "stats_overview_stats_overview_get", requestSchema: null, responseSchema: StatsOverviewResponseSchema },
  { method: "GET", path: "/eval/summary", operationId: "eval_summary_eval_summary_get", requestSchema: null, responseSchema: EvalSummaryResponseSchema },
  { method: "GET", path: "/decisions", operationId: "decisions_decisions_get", requestSchema: null, responseSchema: DecisionsResponseSchema },
  { method: "GET", path: "/progress", operationId: "progress_progress_get", requestSchema: null, responseSchema: ProgressResponseSchema },
  { method: "GET", path: "/router/models", operationId: "router_models_router_models_get", requestSchema: null, responseSchema: RouterModelsResponseSchema },
  { method: "GET", path: "/router/chains", operationId: "router_chains_router_chains_get", requestSchema: null, responseSchema: RouterChainsResponseSchema },
  { method: "GET", path: "/router/usage", operationId: "router_usage_router_usage_get", requestSchema: null, responseSchema: RouterUsageResponseSchema },
  { method: "GET", path: "/ingest/doc-types", operationId: "ingest_doc_types_ingest_doc_types_get", requestSchema: null, responseSchema: null },
  { method: "POST", path: "/ingest/documents", operationId: "ingest_document_ingest_documents_post", requestSchema: null, responseSchema: IngestDocumentAcceptedSchema },
  { method: "GET", path: "/ingest/jobs", operationId: "list_ingest_jobs_ingest_jobs_get", requestSchema: null, responseSchema: IngestJobListResponseSchema },
  { method: "GET", path: "/ingest/jobs/{job_id}", operationId: "get_ingest_job_ingest_jobs__job_id__get", requestSchema: null, responseSchema: IngestJobSchema },
  { method: "GET", path: "/ingest/jobs/{job_id}/report", operationId: "ingest_job_report_ingest_jobs__job_id__report_get", requestSchema: null, responseSchema: null },
  { method: "POST", path: "/ingest/satellite-refresh", operationId: "satellite_refresh_ingest_satellite_refresh_post", requestSchema: SatelliteRefreshRequestSchema, responseSchema: SatelliteRefreshAcceptedSchema },
  { method: "GET", path: "/ingest/satellite/status", operationId: "satellite_status_ingest_satellite_status_get", requestSchema: null, responseSchema: SatelliteStatusResponseSchema },
  { method: "GET", path: "/health", operationId: "health_health_get", requestSchema: null, responseSchema: null },
];
