"""Pydantic request/response models for app/api routers (excluding workspace models, which live in
app/workspace/models.py). These drive the published OpenAPI schema, and therefore the zod schemas
generated by scripts/gen_schemas.py (`make gen-schemas`) — keep them stable and versioned (D-011).
"""
from __future__ import annotations

from datetime import date, datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

# -------------------------------------------------------------------------------------- runs

class Attachment(BaseModel):
    """An uploaded file or GeoJSON reference attached to a run request (app/agent/CONTRACT.md §1:
    `path` is a server-local file the API already stored, e.g. data/uploads/<run_id>/<name>).
    File upload itself (multipart -> path) is a P6 TODO; for now `path` may be pre-populated by a
    caller that already has server-local test fixtures."""

    id: str
    kind: Literal["pdf", "image", "geojson", "csv", "text"] | None = None
    name: str = ""
    path: str | None = None
    media_type: str | None = None
    size_bytes: int | None = None


class RunCreateRequest(BaseModel):
    request: str
    attachments: list[Attachment] = Field(default_factory=list)
    workspace_id: str | None = None
    domain: Literal["land_acquisition", "agri_claims"] | None = None
    lang: Literal["en", "ta"] | None = None
    chaos: str | None = None  # e.g. "gemini:down,groq:slow" (app/router/chaos.py); this run only


class RunCreateResponse(BaseModel):
    run_id: str


class ClarifyRequest(BaseModel):
    answer: str


class RunPublicState(BaseModel):
    """Mirrors `RunState.public_dict()` (app/agent/CONTRACT.md §3 / app/agent/state.py `RunState`).
    Reconstructed from persisted `run_event` rows by app.api.run_store until
    `app.agent.get_run_state(run_id)` is wired in (app/api/runner.py); field names match the
    contract exactly so that swap is a no-op for API consumers. `steps`/`verdicts` are keyed by id
    (dicts, not lists), matching RunState; `errors` (plural) matches the contract's field name."""

    run_id: str
    workspace_id: str | None = None
    contract_version: str = "1"
    request: str
    lang: Literal["en", "ta"] = "en"
    domain: str = "land_acquisition"
    attachments: list[Attachment] = Field(default_factory=list)
    status: Literal["queued", "running", "clarify", "done", "failed"]
    created_at: datetime
    updated_at: datetime
    slots: dict[str, Any] = Field(default_factory=dict)
    missing_info: list[dict[str, Any]] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)
    plan: dict[str, Any] | None = None
    steps: dict[str, dict[str, Any]] = Field(default_factory=dict)
    claims: list[dict[str, Any]] = Field(default_factory=list)
    critic: list[dict[str, Any]] = Field(default_factory=list)
    verdicts: dict[str, dict[str, Any]] = Field(default_factory=dict)
    reroutes: int = 0
    workspace: dict[str, Any] | None = None
    narrative: dict[str, Any] = Field(default_factory=dict)
    route_trace: list[dict[str, Any]] = Field(default_factory=list)
    telemetry: dict[str, Any] = Field(default_factory=dict)
    ledger_head: str | None = None
    errors: list[dict[str, Any]] = Field(default_factory=list)
    degraded: bool = False


# -------------------------------------------------------------------------------------- documents

class DocumentSummary(BaseModel):
    id: int
    sha256: str
    path: str
    classified_type: str | None = None
    scheme_relevance: str | None = None
    village: str | None = None
    unit_no: str | None = None
    block_no: str | None = None
    doc_no: str | None = None
    doc_date: date | None = None
    pages: int
    status: str
    stage: str | None = None
    folder_label: str | None = None
    folder_type_mismatch: bool = False


class DocumentListResponse(BaseModel):
    items: list[DocumentSummary]
    total: int
    limit: int
    offset: int


# -------------------------------------------------------------------------------------- evidence

class OwnerRef(BaseModel):
    """An owner attached to an extraction row. `name` is null unless demo_mask=false is both
    requested AND allowed by server config (ALLOW_DEMO_UNMASK=true, local only — D-032/D-033)."""

    position: int
    token: str            # stable pseudonymous token, always present
    relation: str | None = None
    legal_heirs: bool = False
    name: str | None = None  # PII: only populated when unmasking was requested and allowed


class EvidenceResponse(BaseModel):
    extraction_id: int
    document_id: int | None = None
    page_id: int | None = None
    page_no: int | None = None
    page_ref: str | None = None
    schema_name: str
    doc_type: str | None = None
    bbox: list[float] | None = None
    bbox_method: str | None = None
    extractor: str | None = None
    privacy_tier: str
    confidence: float | None = None
    review_status: str
    row: dict[str, Any]
    owners: list[OwnerRef] = Field(default_factory=list)
    masked: bool = True


# -------------------------------------------------------------------------------------- review queue

class ReviewItem(BaseModel):
    id: int
    content_hash: str
    document_id: int | None = None
    page_id: int | None = None
    page_ref: str | None = None
    extraction_id: int | None = None
    reason: str
    detail: dict[str, Any] = Field(default_factory=dict)
    status: Literal["open", "decided", "dismissed"]
    decided_value: dict[str, Any] | None = None
    decided_by: str | None = None
    decided_at: datetime | None = None
    created_at: datetime


class ReviewListResponse(BaseModel):
    items: list[ReviewItem]
    total: int


class ReviewDecisionRequest(BaseModel):
    decision: Literal["approved", "corrected", "rejected"]
    corrected_value: dict[str, Any] | None = None
    decided_by: str | None = None


class ReviewDecisionResponse(BaseModel):
    id: int
    status: str
    extraction_id: int | None = None
    review_status: str | None = None  # the linked extraction's new review_status, when applicable


# -------------------------------------------------------------------------------------- examples

class ExampleQuery(BaseModel):
    id: str
    text: str
    category: str | None = None


class ExamplesResponse(BaseModel):
    items: list[ExampleQuery]


# -------------------------------------------------------------------------------------- stats

class KpiValue(BaseModel):
    """One overview number with the query/file that produced it (ui-spec.md: 'each with a source
    string')."""

    id: str
    label: str
    value: Any
    unit: str | None = None
    source: str
    breakdown: dict[str, Any] | None = None


class StatsOverviewResponse(BaseModel):
    kpis: list[KpiValue]
    phase_status: dict[str, Any] | None = None
    generated_at: datetime


# -------------------------------------------------------------------------------------- parcels

class ParcelDetail(BaseModel):
    parcel_uid: str
    village: str | None = None
    kide: str | None = None
    survey_no: str | None = None
    sub_div: str | None = None
    unit_id: int | None = None
    block_id: int | None = None
    area_ha_gis: float | None = None
    area_ha_utm: float | None = None
    inside_park_boundary: bool | None = None
    current_stage: str | None = None
    stage_entered: date | None = None
    days_in_stage: int | None = None
    evidence_level: str | None = None
    stalled_flag: str | None = None
    n_findings: int = 0
    source: str = "parcel + v_parcel_lifecycle + finding (db/views/050_lifecycle.sql)"


class TimelineEvent(BaseModel):
    event_id: int | None = None
    stage: str
    event_date: date | None = None
    date_precision: str | None = None
    document_id: int | None = None
    extraction_id: int | None = None
    link_kind: str | None = None


class SeasonState(BaseModel):
    ag_year: int
    season: str
    state: str | None = None
    p_state: float | None = None
    route: str | None = None
    needs_field: bool = False


class SeriesPoint(BaseModel):
    date: date
    ndvi: float | None = None
    bsi: float | None = None
    ndwi: float | None = None
    supported: bool | None = None


class ParcelTimelineResponse(BaseModel):
    parcel_uid: str
    events: list[TimelineEvent]
    series: list[SeriesPoint]
    season_states: list[SeasonState]
    source: str = ("acquisition_event via v_parcel_events (db/views/050_lifecycle.sql); "
                   "data/s2/smoothed.parquet (5-day smoothed NDVI/BSI/NDWI); parcel_season")


class ParcelExtractionRow(BaseModel):
    extraction_id: int
    fact_type: str | None = None
    document_id: int | None = None
    page_no: int | None = None
    bbox: list[float] | None = None
    bbox_method: str | None = None
    confidence: float | None = None
    self_consistency: str | None = None
    owner_read_status: str | None = None
    review_status: str | None = None
    row: dict[str, Any]


class ParcelExtractionsResponse(BaseModel):
    parcel_uid: str
    items: list[ParcelExtractionRow]
    total: int
    source: str = "parcel_fact + acquisition_event joined to extraction (extraction_id)"


class DidRow(BaseModel):
    event: str
    metric: str
    season_scope: str
    event_date: date | None = None
    n_pre: int | None = None
    n_post: int | None = None
    pre_diff: float | None = None
    post_diff: float | None = None
    did: float | None = None
    ci_lo: float | None = None
    ci_hi: float | None = None
    farmland_like_p: float | None = None


class ParcelSatelliteResponse(BaseModel):
    parcel_uid: str
    did: list[DidRow]
    season_states: list[SeasonState]
    chips: list[str]
    source: str = "parcel_did; parcel_season; cached chips under planet.chips.render.CHIP_DIR"


# -------------------------------------------------------------------------------------- findings

class FindingItem(BaseModel):
    id: int
    finding_key: str
    category: str
    severity: str
    confidence: float
    parcel_uid: str | None = None
    village: str | None = None
    unit_id: int | None = None
    block_id: int | None = None
    title: str
    evidence_level: str
    verdict: str | None = None
    status: str
    caveats: list[str] = Field(default_factory=list)
    created_at: datetime


class FindingListResponse(BaseModel):
    items: list[FindingItem]
    total: int
    limit: int
    offset: int
    source: str = "finding table (db/migrations/0014_findings.sql)"


class FindingSummaryRow(BaseModel):
    category: str
    severity: str
    evidence_level: str
    n: int
    avg_conf: float


class FindingSummaryResponse(BaseModel):
    items: list[FindingSummaryRow]
    source: str = "v_finding_summary (db/views/070_findings.sql)"


class IdleLandRow(BaseModel):
    finding_id: int
    village: str | None = None
    unit_id: int | None = None
    block_id: int | None = None
    idle_ha: float | None = None
    n_parcels: int | None = None
    oldest_possession: date | None = None
    min_major_road_km: float | None = None
    min_substation_km: float | None = None
    evidence_level: str
    confidence: float


class IdleLandResponse(BaseModel):
    items: list[IdleLandRow]
    source: str = "v_idle_land_bank (db/views/050_lifecycle.sql)"


class EvidencePackResponse(BaseModel):
    finding_id: int
    pack: dict[str, Any]
    source: str = "pipeline.findings.evidence_pack.evidence_pack()"


# -------------------------------------------------------------------------------------- classifier

class ClassifierSummaryResponse(BaseModel):
    metrics: list[dict[str, Any]]
    live_distribution: list[dict[str, Any]]
    folder_vs_classified_mismatch: int
    source: str = "docs/metrics.md (Classifier rows) + document table (live)"


# -------------------------------------------------------------------------------------- router / models

class RouterModelsResponse(BaseModel):
    models: list[dict[str, Any]]
    doctor: dict[str, Any] | None = None
    source: str = "config/models.yaml + data/doctor.json"


class RouterUsageResponse(BaseModel):
    by_model_task: list[dict[str, Any]]
    latency: list[dict[str, Any]]
    pii_audit: dict[str, Any]
    source: str = "data/router_log.sqlite"


class RouterChainsResponse(BaseModel):
    tasks: list[dict[str, Any]]
    source: str = "config/models.yaml (tasks:)"


# -------------------------------------------------------------------------------------- eval / decisions / progress

class EvalSummaryResponse(BaseModel):
    rows: list[dict[str, Any]]
    files: dict[str, Any]
    source: str = "docs/metrics.md + eval/**/*.json"


class Decision(BaseModel):
    id: str
    date: str | None = None
    decision: str
    by: str | None = None
    context: str | None = None


class DecisionsResponse(BaseModel):
    items: list[Decision]
    source: str = "docs/decisions.md"


class ProgressResponse(BaseModel):
    overall_pct: str | None = None
    phases: list[dict[str, Any]]
    raw_markdown: str
    source: str = "docs/progress.md"


# -------------------------------------------------------------------------------------- runs / ledger

class RunSummary(BaseModel):
    id: str
    workspace_id: str | None = None
    status: str
    request: str | None = None
    created_at: datetime
    updated_at: datetime


class RunListResponse(BaseModel):
    items: list[RunSummary]
    total: int
    limit: int
    offset: int


class LedgerVerifyResponse(BaseModel):
    run_id: str
    ok: bool
    first_bad_seq: int | None = None
    n_entries: int
    head_hash: str | None = None


class RunTraceResponse(BaseModel):
    """Router candidates/scores/filtered reasons, critic/judge detail and the ledger hash for one
    run — assembled after the fact from `run_event` (+ `router_log` when correlated by run_id) for
    any event field the agent didn't stream live (app/agent/CONTRACT.md route_trace lives only in
    the terminal `result` event's RunState/WorkspaceSpec today)."""

    run_id: str
    route_trace: list[dict[str, Any]]
    critic: list[dict[str, Any]]
    judge: list[dict[str, Any]]
    fallbacks: list[dict[str, Any]]
    ledger_head: str | None = None
    router_log: list[dict[str, Any]] = Field(default_factory=list)
    source: str = "run_event (this run) + data/router_log.sqlite (run_id match, if any)"


# -------------------------------------------------------------------------------------- ingest

class IngestStage(BaseModel):
    name: str
    status: Literal["pending", "running", "done", "skipped", "failed"]
    started_at: datetime | None = None
    finished_at: datetime | None = None
    detail: str | None = None


class IngestJob(BaseModel):
    """A background ingest job (new-document upload or satellite refresh). See
    app/api/routers/ingest.py for the stage list of each `kind` and how each stage's `detail` is
    populated."""

    id: int
    kind: Literal["document", "satellite"]
    status: Literal["queued", "running", "done", "failed", "duplicate"]
    filename: str | None = None
    created_at: datetime
    started_at: datetime | None = None
    finished_at: datetime | None = None
    document_id: int | None = None
    stages: list[IngestStage]
    result: dict[str, Any] | None = None
    error: str | None = None


class IngestJobListResponse(BaseModel):
    jobs: list[IngestJob]


class IngestDocumentAccepted(BaseModel):
    job_id: int
    status: Literal["queued", "duplicate"]
    duplicate_of: int | None = None


class SatelliteRefreshRequest(BaseModel):
    max_scenes: int | None = None


class SatelliteRefreshAccepted(BaseModel):
    job_id: int


class SatelliteStatusResponse(BaseModel):
    latest_scene_date: date | None = None
    scene_count: int
    last_refresh_at: datetime | None = None
    running_job_id: int | None = None
