"""`make gen-schemas`: convert the FastAPI OpenAPI document into zod schemas for the frontend
(D-011: React + JS, no TypeScript — request/response shapes are validated at runtime with zod
instead of compile-time types).

Writes `web/src/api/schemas.js`, exporting one `z.object(...)` (or `z.enum(...)`) per OpenAPI
component schema, named `<ComponentName>Schema`, plus a small `endpoints` map (method, path,
requestSchema, responseSchema) the frontend's fetch wrapper can use directly.

The conversion covers the JSON Schema subset FastAPI/Pydantic actually emits: object/array/string/
integer/number/boolean, $ref, enum, anyOf (used for `Optional[...]`/nullable), format hints
(date/date-time -> z.string(), left as string; the frontend parses dates explicitly), and
additionalProperties (free-form dict -> z.record(z.any())). It intentionally does not depend on
any npm package, so it can run under `uv run` with no Node toolchain.
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / "web" / "src" / "api" / "schemas.js"

_HEADER = """\
// AUTO-GENERATED by `make gen-schemas` (scripts/gen_schemas.py) from the FastAPI OpenAPI document.
// Do not edit by hand — regenerate after any app/api schema change (D-011).
import { z } from "zod";

"""


def _safe_name(ref_name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", ref_name)


def _ref_name(ref: str) -> str:
    return _safe_name(ref.rsplit("/", 1)[-1])


def _scalar(schema: dict) -> str | None:
    t = schema.get("type")
    if t == "string":
        return "z.string()"
    if t == "integer":
        return "z.number().int()"
    if t == "number":
        return "z.number()"
    if t == "boolean":
        return "z.boolean()"
    if t == "null":
        return "z.null()"
    return None


def schema_to_zod(schema: dict, components: dict) -> str:
    if not schema:
        return "z.any()"
    if "$ref" in schema:
        return f"{_ref_name(schema['$ref'])}Schema"
    if "allOf" in schema and len(schema["allOf"]) == 1:
        return schema_to_zod(schema["allOf"][0], components)
    if "anyOf" in schema or "oneOf" in schema:
        variants = schema.get("anyOf") or schema.get("oneOf")
        non_null = [v for v in variants if v.get("type") != "null"]
        nullable = len(non_null) != len(variants)
        if len(non_null) == 1:
            expr = schema_to_zod(non_null[0], components)
        else:
            expr = "z.union([" + ", ".join(schema_to_zod(v, components) for v in non_null) + "])"
        return expr + ".nullable()" if nullable else expr
    if "enum" in schema:
        vals = schema["enum"]
        if all(isinstance(v, str) for v in vals):
            return "z.enum([" + ", ".join(json.dumps(v) for v in vals) + "])"
        return "z.union([" + ", ".join(json.dumps(v) for v in vals) + "].map((v) => z.literal(v)))"
    t = schema.get("type")
    if t == "array":
        item = schema_to_zod(schema.get("items", {}), components)
        return f"z.array({item})"
    if t == "object" or "properties" in schema:
        props = schema.get("properties", {})
        required = set(schema.get("required", []))
        if not props:
            return "z.record(z.any())"
        lines = []
        for name, sub in props.items():
            expr = schema_to_zod(sub, components)
            if name not in required and not expr.endswith(".nullable()"):
                expr += ".optional()"
            lines.append(f"  {json.dumps(name)}: {expr}")
        return "z.object({\n" + ",\n".join(lines) + ",\n})"
    scalar = _scalar(schema)
    if scalar:
        return scalar
    return "z.any()"


def build(openapi: dict) -> str:
    components = openapi.get("components", {}).get("schemas", {})
    out = [_HEADER]
    # Two passes: emit in a stable, dependency-friendly order (alphabetical is fine; zod schemas
    # reference each other by name and JS allows forward references inside function bodies, but
    # top-level `const` does not — so every ref is wrapped in z.lazy() to be safe).
    for name in sorted(components):
        zod = schema_to_zod(components[name], components)
        safe = _safe_name(name)
        out.append(f"export const {safe}Schema = z.lazy(() => ({zod}));\n")

    endpoints = []
    for path, methods in openapi.get("paths", {}).items():
        for method, op in methods.items():
            if method not in ("get", "post", "put", "delete", "patch"):
                continue
            resp_schema = None
            responses = op.get("responses", {})
            # 202 Accepted: the ingest endpoints (app/api/routers/ingest.py) return it for
            # background jobs; their response body is still a normal JSON schema to convert.
            ok = responses.get("200") or responses.get("201") or responses.get("202")
            if ok:
                content = ok.get("content", {}).get("application/json", {})
                ref = content.get("schema", {})
                resp_schema = f"{_ref_name(ref['$ref'])}Schema" if "$ref" in ref else None
            req_schema = None
            body = op.get("requestBody", {}).get("content", {}).get("application/json", {})
            ref = body.get("schema", {})
            if "$ref" in ref:
                req_schema = f"{_ref_name(ref['$ref'])}Schema"
            endpoints.append({
                "method": method.upper(), "path": path, "operationId": op.get("operationId"),
                "requestSchema": req_schema, "responseSchema": resp_schema,
            })

    out.append("export const endpoints = [\n")
    for e in endpoints:
        out.append(
            "  {{ method: {}, path: {}, operationId: {}, requestSchema: {}, responseSchema: {} }},\n".format(
                json.dumps(e["method"]), json.dumps(e["path"]), json.dumps(e["operationId"]),
                e["requestSchema"] or "null", e["responseSchema"] or "null")
        )
    out.append("];\n")
    return "".join(out)


def main() -> None:
    sys.path.insert(0, str(ROOT))
    from dotenv import load_dotenv

    load_dotenv(ROOT / ".env")
    from app.api.main import app

    openapi = app.openapi()
    js = build(openapi)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(js, encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(ROOT)} ({len(openapi.get('components', {}).get('schemas', {}))} "
         f"schemas, {len(js.splitlines())} lines)")


if __name__ == "__main__":
    main()
